version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: chattingo-db
    env_file:
      - ./backend/.env         # <-- load same env file for db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    image: wiings09/chattingo-backend:latest
    container_name: chattingo-backend
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    image: wiings09/chattingo-frontend:latest
    container_name: chattingo-frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "3000:80"

volumes:
  db-data:
