version: "3.9"

services:
  db:
    image: mysql:8.1
    container_name: chattingo-db
    env_file:
      - ./backend/.env         # <-- load same env file for db
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: wiings09/chattingo-backend:${TAG}
    container_name: chattingo-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: wiings09/chattingo-frontend:${TAG}
    container_name: chattingo-frontend
    environment:
      - REACT_APP_API_URL=http://72.60.111.17.nip.io:8000
    ports:
      - "80"

volumes:
  db-data:
